### PR TITLE
/proc/diskstats: better detection of unused block devices

### LINKED ISSUE #5: --disk-wait is broken
##### SUMMARY

```
% ./dool --disk-wait 
/home/leah/src/dool/./dool:2683: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/leah/src/dool/./dool", line 2899, in <module>
    main()
  File "/home/leah/src/dool/./dool", line 2751, in main
    scheduler.run()
  File "/usr/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/leah/src/dool/./dool", line 2847, in perform
    o.extract()
  File "<string>", line 68, in extract
KeyError: 'rd_ios'
```

##### ISSUE TYPE

 - Bug Report

##### DSTAT VERSION
```
Dool 0.9.9
Written by Scott Baker <scott@perturb.org>
Forked from Dstat written by Dag Wieers <dag@wieers.com>
Homepage at https://github.com/scottchiefbaker/dool/

Platform posix/linux
Kernel 5.10.14_1
Python 3.9.2 (default, Mar  5 2021, 11:40:33) 
[GCC 10.2.1 20201203]

Terminal type: rxvt-unicode-256color (color support)
Terminal size: 44 lines, 160 columns

Processors: 8
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio,cpu,cpu-adv,cpu-use,cpu24,disk,disk24,disk24-old,epoch,fs,int,int24,io,ipc,load,lock,mem,mem-adv,net,page,page24,proc,raw,
	socket,swap,swap-old,sys,tcp,time,udp,unix,vm,vm-adv,zones
/home/leah/src/dool/plugins:
	battery,battery-remain,condor-queue,cpufreq,dbus,disk-avgqu,disk-avgrq,disk-svctm,disk-tps,disk-util,disk-wait,dool,dool-cpu,dool-ctxt,
	dool-mem,fan,freespace,fuse,gpfs,gpfs-ops,helloworld,ib,innodb-buffer,innodb-io,innodb-ops,jvm-full,jvm-vm,lustre,md-status,
	memcache-hits,mongodb-conn,mongodb-mem,mongodb-opcount,mongodb-queue,mongodb-stats,mysql-io,mysql-keys,mysql5-cmds,mysql5-conn,
	mysql5-innodb,mysql5-innodb-basic,mysql5-innodb-extra,mysql5-io,mysql5-keys,net-packets,nfs3,nfs3-ops,nfsd3,nfsd3-ops,nfsd4-ops,nfsstat4,
	ntp,postfix,power,proc-count,qmail,redis,rpc,rpcd,sendmail,snmp-cpu,snmp-load,snmp-mem,snmp-net,snmp-net-err,snmp-sys,snooze,squid,
	test,thermal,top-bio,top-bio-adv,top-childwait,top-cpu,top-cpu-adv,top-cputime,top-cputime-avg,top-int,top-io,top-io-adv,top-latency,
	top-latency-avg,top-mem,top-oom,utmp,vm-cpu,vm-mem,vm-mem-adv,vmk-hba,vmk-int,vmk-nic,vz-cpu,vz-io,vz-ubc,wifi,zfs-arc,zfs-l2arc,
	zfs-zil
```

##### OS / ENVIRONMENT

Void Linux, x86_64 glibc.

##### STEPS TO REPRODUCE

Just run it like above.

##### EXPECTED RESULTS

Output of disk wait times.

##### ACTUAL RESULTS

KeyError

p.s.: if you tag a release, I'll package dool for Void Linux.

### PR DESCRIPTION
**Pull request by leahneukirchen**
##### ISSUE TYPE

 - Bugfix pull-request

##### DSTAT VERSION
```
Dool 1.0.0
Written by Scott Baker <scott@perturb.org>
Forked from Dstat written by Dag Wieers <dag@wieers.com>
Homepage at https://github.com/scottchiefbaker/dool/

Platform posix/linux
Kernel 5.13.12_1
Python 3.10.2 (main, Jan 15 2022, 03:11:32) [GCC 10.2.1 20201203]

Terminal type: rxvt-unicode-256color (color support)
Terminal size: 82 lines, 154 columns

Processors: 8
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio,cpu,cpu-adv,cpu-use,cpu24,disk,disk24,disk24-old,epoch,fs,int,int24,io,ipc,load,lock,mem,mem-adv,net,page,page24,proc,
	raw,socket,swap,swap-old,sys,tcp,time,udp,unix,vm,vm-adv,zones
/home/leah/src/dool/plugins:
	battery,battery-remain,condor-queue,cpufreq,dbus,disk-avgqu,disk-avgrq,disk-svctm,disk-tps,disk-util,disk-wait,dool,dool-cpu,
	dool-ctxt,dool-mem,fan,freespace,fuse,gpfs,gpfs-ops,helloworld,ib,innodb-buffer,innodb-io,innodb-ops,jvm-full,jvm-vm,lustre,
	md-status,memcache-hits,mongodb-conn,mongodb-mem,mongodb-opcount,mongodb-queue,mongodb-stats,mysql-io,mysql-keys,mysql5-cmds,
	mysql5-conn,mysql5-innodb,mysql5-innodb-basic,mysql5-innodb-extra,mysql5-io,mysql5-keys,net-packets,nfs3,nfs3-ops,nfsd3,nfsd3-ops,
	nfsd4-ops,nfsstat4,ntp,postfix,power,proc-count,qmail,redis,rpc,rpcd,sendmail,snmp-cpu,snmp-load,snmp-mem,snmp-net,snmp-net-err,
	snmp-sys,snooze,squid,test,thermal,top-bio,top-bio-adv,top-childwait,top-cpu,top-cpu-adv,top-cputime,top-cputime-avg,top-int,
	top-io,top-io-adv,top-latency,top-latency-avg,top-mem,top-oom,utmp,vm-cpu,vm-mem,vm-mem-adv,vmk-hba,vmk-int,vmk-nic,vz-cpu,vz-io,
	vz-ubc,wifi,zfs-arc,zfs-l2arc,zfs-zil
```

##### SUMMARY

The format of /proc/diskstats has changed over the years:
Until kernel 4.17 there were 14 fields (which this code assumed)
Since 4.18 there are 18 fields, since 5.5 there are 20 fields.

Assume unused devices have all fields zero.

Fixes #1.
Fixes #5.
Fixes #7.

```
% ./dool --disk-wait                      
--loop0----nvme0n1----zram0--                  
rawa wawa:rawa wawa:rawa wawa
0.05    0:0.16 2.46:0.00 0.01
   0    0:   0    0:   0    0
   0    0:   0 1.67:   0    0^C
```

### CODE REVIEW

**Comment by leahneukirchen** [comment]
#1 is similar btw.

**Comment by leahneukirchen** [comment]
I realized this issue occurs all over the code base and fixed it everywhere.

**Comment by scottchiefbaker** [comment]
Apologies... Github was **not** sending me alerts for issues and pull requests on this repo. I did not see this until just now.

Is this still relevant? I'm working through some backlog.

**Comment by leahneukirchen** [comment]
Yes, it's still relevant (even more so as people don't run <4.17 kernels anymore really).

**Comment by leahneukirchen** [comment]
it means "make a set out of the items from the 4th" and "check it's the same set that contains only "0", i.e. it checks all items are "0".

**Pull request merged**
